[tox]
skipsdist = True
envlist = lint,cover,mypy
sitepackages = False
skip_missing_interpreters = False
minversion = 3.18.0

[vars]
src_path = {toxinidir}/manila_data/
tst_path = {toxinidir}/tests/
pyproject_toml = {toxinidir}/pyproject.toml
all_path = {[vars]src_path} {[vars]tst_path}
uv_flags = --frozen --isolated --extra=dev

[testenv]
usedevelop = True
basepython = python3
allowlist_externals =
    uv
setenv = OS_STDOUT_CAPTURE=1
         OS_STDERR_CAPTURE=1
         OS_TEST_TIMEOUT=60
         PYTHONPATH = {toxinidir}:{[vars]src_path}
passenv =
    PYTHONPATH
    HOME
commands = uv run {[vars]uv_flags} stestr run --slowest {posargs}

[testenv:fmt]
description = Apply coding style standards to code
deps =
    black
    isort
commands =
    isort {[vars]all_path}
    black --config {[vars]pyproject_toml} {[vars]all_path}

[testenv:lint]
description = Check code against coding style standards
deps =
    black
    flake8
    flake8-docstrings
    flake8-copyright
    flake8-builtins
    pyproject-flake8
    pep8-naming
    isort
    codespell
commands =
    codespell {[vars]all_path}
    # pflake8 wrapper supports config from pyproject.toml
    pflake8 --exclude --config {toxinidir}/pyproject.toml {[vars]all_path}
    isort --check-only --diff {[vars]all_path}
    black --config {[vars]pyproject_toml} --check --diff {[vars]all_path}

[testenv:mypy]
commands =
    uv run {[vars]uv_flags} mypy {[vars]src_path}

[testenv:cover]
setenv =
    VIRTUAL_ENV={envdir}
commands =
    uv run {[vars]uv_flags} coverage erase
    uv run {[vars]uv_flags} coverage run -m stestr run --slowest {posargs}
    uv run {[vars]uv_flags} coverage combine
    uv run {[vars]uv_flags} coverage html -d cover
    uv run {[vars]uv_flags} coverage xml -o cover/coverage.xml
    uv run {[vars]uv_flags} coverage report

[testenv:lock]
description = Update lock file
commands =
    uv lock --upgrade --no-cache
