name: Build Snap

on:
  workflow_call:
    outputs:
      snap:
        description: "Filename of the built snap artifact"
        value: local-${{ jobs.build.outputs.snap }}

  schedule:
    - cron: '22 4 */2 * *'

jobs:
  build:
    name: Build snap
    runs-on: ubuntu-latest
    outputs:
      snap: ${{ steps.snapcraft.outputs.snap }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build snap locally
        uses: canonical/action-build@v1.3.0
        id: snapcraft

      - name: Upload locally built snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: local-${{ steps.snapcraft.outputs.snap }}
          path: ${{ steps.snapcraft.outputs.snap }}
